### ISSUE TITLE
Container support for v3

### ISSUE THREAD

**Issue by ldrrp** [SiloCityLabs/docker-nas#52]
## Problem

Paths were updated and all container compose files and paths need to be updated to match.

## Containers to be tested:

- [x] ~~ark~~ Needs to be replaced with newer container. Created app request #62
- [x] collabora
- [x] ~~heimdall~~ Moved to separate issue #23 
- [x] homeassistant
- [x] minecraft
- [x] minecraft-bedrock
- [x] nextcloud
- [x] nginx
- [x] ~~nzbget~~ - Moved into separate issue, This never worked in v2 yet. #57 
- [x] ~~onlyoffice~~ Dropping support for this app since collabora seems to be the preference by nextcloud team.
- [x] phpmyadmin
- [x] plex
- [x] portainer
- [x] prowlarr
- [x] radarr
- [x] samba
- [x] sonarr
- [x] transmission

**Comment by ldrrp** [comment]
Need to make some tweaks to nextcloud

```
    The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster.
        Missing index "fs_id_storage_size" in table "oc_filecache".
        Missing index "fs_storage_path_prefix" in table "oc_filecache".
        Missing index "properties_pathonly_index" in table "oc_properties".
        Missing index "job_lastcheck_reserved" in table "oc_jobs".
    Module php-imagick in this instance has no SVG support. For better compatibility it is recommended to install it.
```
